services:
  postgres:
    image: pgvector/pgvector:0.8.5-pg17
    container_name: ai-workspace-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER in docker/.env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in docker/.env}
      POSTGRES_DB: ${POSTGRES_DB:?Set POSTGRES_DB in docker/.env}
    ports:
      - "5434:5432"
    volumes:
      - ai_workspace_postgres_data:/var/lib/postgresql/data
  postgres-search:
    image: paradedb/paradedb:latest
    container_name: ai-workspace-search-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Set POSTGRES_USER in docker/.env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in docker/.env}
      POSTGRES_DB: ${POSTGRES_DB:?Set POSTGRES_DB in docker/.env}
    ports:
      - "5435:5432"
    volumes:
      - ai_workspace_search_postgres_data:/var/lib/postgresql/

  redis:
    image: redis:8
    container_name: ai-workspace-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ai_workspace_redis_data:/data
    
  minio:
    image: minio/minio:latest
    container_name: ai-workspace-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?Set MINIO_ROOT_USER in docker/.env}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?Set MINIO_ROOT_PASSWORD in docker/.env}
    volumes:
      - ./minio/data:/data
    command:
      server /data --console-address ":9001"


volumes:
  ai_workspace_postgres_data:
  ai_workspace_search_postgres_data:
  ai_workspace_redis_data:
  ai_workspace_minio_data:
